# SOPS Configuration
# This file defines encryption rules for secrets management

creation_rules:
  # Encrypt .env file with age
  - path_regex: \.env$
    age: >-
      age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    # Replace the above with your age public key
    # Generate with: age-keygen -o ~/.config/sops/age/keys.txt
    # Your public key will be displayed when you generate it
    
  # You can add more rules for other file patterns
  # - path_regex: secrets/.*\.yaml$
  #   age: >-
  #     age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

